### ISSUE TITLE
Add support for Github Meta API

### ISSUE THREAD

**Issue by chris-rock** [gittalk/git-hook#4]
https://developer.github.com/v3/meta/ to guard against wrong requests

**Comment by atmos** [comment]
There's also [signed requests](https://developer.github.com/webhooks/#payloads) if you configure a hook secret.

**Comment by chris-rock** [comment]
You mean: `X-Hub-Signature`?

**Comment by chris-rock** [comment]
@atmos Thanks for bringing this up.

**Comment by atmos** [comment]
Yup
